name: "validate"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  checks:
    uses: aztfmods/validor/.github/workflows/validate.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
